### ISSUE TITLE
Ilia keybindings not working after upgrading to 4.3.3-1regolith-jammy

### ISSUE THREAD

**Issue by hemker** [regolith-linux/regolith-wm-config#13]
Hey,
after upgrading the whole packageset to latest 4.3.3 releases, keybindings related to ilia are not working anymore. Super + Space does not open the launcher app. If you take a look into the `/usr/share/regolith/common/config-.d` folder in this repository, you can see that the `20_ilia` file has been removed.

Is it placed somewhere else now?

Best and thank you.

**Comment by kgilmer** [comment]
Hi @hemker , thanks for reporting the issue.  The package that needs to be installed is `regolith-i3-ilia` to restore the launcher app keybindings.

**Comment by hemker** [comment]
Hi @kgilmer, thanks for the fast reply! Installing the mentioned package brings the ilia keybindings back to live. Thanks!
