### ISSUE TITLE
How to override partials in `common` folder

### ISSUE THREAD

**Issue by stoopkidddd** [regolith-linux/regolith-wm-config#16]
Not sure if this is the right repository for this - but the [documentation states here ](https://regolith-desktop.com/docs/howtos/customize-i3-configuration/#how-to-customize-a-default-partial) how to override a default partial.

However it looks like a bunch of partials are in a `common` folder now. I tried overriding one of those by putting it in both the `i3` folder and/or the `common` folder in `~/.config/regolith3/` but neither seem to work.

Is it impossible to override anything in `common`? Or am I missing something?

**Comment by kgilmer** [comment]
Hi @stoopkidddd , by not working, are you getting a conflict error or are you simply not seeing the keybinding?  My apologies for the confusing documentation.  It should not matter where the partial is as long as you can uninstall the package that is providing it.  For example:

```
~/dev/repos$ ls /usr/share/regolith/common/config.d/
15_base_launchers    30_navigation        40_i3-swap-focus     40_workspace-config  50_resize-mode       82_rofication-ilia   84_ftue              88_network-manager   
~/dev/repos$ ls /usr/share/regolith/common/config.d/82_rofication-ilia 
/usr/share/regolith/common/config.d/82_rofication-ilia
~/dev/repos$ dpkg -S 82_rofication-ilia
regolith-wm-rofication-ilia: /usr/share/regolith/common/config.d/82_rofication-ilia
```

So if you want to override the partial `/usr/share/regolith/common/config.d/82_rofication-ilia` you'd want to copy that into your user partial directory.

For sway: `$HOME/.config/regolith3/sway/config.d/`    ([source](https://github.com/regolith-linux/regolith-wm-config/blob/main/etc/regolith/sway/config#L166))
For i3: `include $HOME/.config/regolith3/i3/config.d/` ([source](https://github.com/regolith-linux/regolith-wm-config/blob/main/etc/regolith/i3/config#L143))

**Comment by stoopkidddd** [comment]
Thank you @kgilmer and definitely no need to apologize. Documentation is great and love this project. Putting the `/common/` partial in the `$HOME/.config/regolith3/i3/config.d` after uninstalling the original worked. I could have sworn I tried that before making the issue. User error - my fault. Thanks again for making an awesome WM setup.
