### ISSUE TITLE
Polkit broken in Regolith 3.1 on Wayland on Linux Mint 21.3

### ISSUE THREAD

**Issue by 70rc** [regolith-linux/regolith-wm-config#20]
Commit b63e6d1b838adf513e92c16f39e4e950d12c096c causes a regression on Linux Mint 21.3 that breaks Polkit. As far as I can tell there are two independent issues with the switch to the Mate Polkit authentication agent:

1. The path to the Mate authentication agent is wrong. On Mint 21.3 it doesn't live under `/usr/libexec/polkit-mate-authentication-agent-1` but rather `/usr/lib/x86_64-linux-gnu/polkit-mate/polkit-mate-authentication-agent-1`.

2. If I run the agent manually under Wayland, it dumps core as soon as I try to open a GUI application that wants to connect to it (I tried Timeshift). Using the original `GDK_BACKEND=x11`, both the GNOME and the Mate authentication agents work fine. So it seems to me that the Mate agent still needs to be run under XWayland rather than natively.

**Comment by kgilmer** [comment]
@SoumyaRanjanPatnaik CC

**Comment by SoumyaRanjanPatnaik** [comment]
Thanks for reporting this issue. 

@kgilmer does this look like a good way to resolve this issue?
```
exec exec $(dpkg -L mate-polkit | grep polkit-mate-authentication-agent-1)
``` 
where `dpkg -L mate-polkit` is: 
```console
$ dpkg -L mate-polkit
/.
/usr
/usr/libexec
/usr/libexec/polkit-mate-authentication-agent-1
/usr/share
/usr/share/doc
/usr/share/doc/mate-polkit
/usr/share/doc/mate-polkit/AUTHORS
/usr/share/doc/mate-polkit/HACKING
/usr/share/doc/mate-polkit/README
/usr/share/doc/mate-polkit/changelog.Debian.gz
/usr/share/doc/mate-polkit/copyright
```

**Comment by SoumyaRanjanPatnaik** [comment]
To address the crash in wayland, it might be a good idea to have a separate package which sets the `GDK_BACKEND=x11` environment variable.

**Comment by SoumyaRanjanPatnaik** [comment]
@70rc as a hotfix, you can `apt remove regolith-sway-polkit` and create a config partial at `~/.config/regolith3/sway/config.d/` (create the dir if it doesn't exist) with either 
```
exec env GDK_BACKEND=x11 /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1
```
or 
```
exec env GDK_BACKEND=x11/usr/lib/x86_64-linux-gnu/polkit-mate/polkit-mate-authentication-agent-1
```
(whatever works for you)

**Comment by kgilmer** [comment]
> @kgilmer does this look like a good way to resolve this issue?

What about simply removing the absolute path and relying on it being provided by the system?  (parsimony)

**Comment by 70rc** [comment]
On Mint, `polkit-mate-authentication-agent-1` is not in my `PATH`. However, there's a package for it: `mate-polkit-bin`, which is literally just a shell script under `/usr/bin` calling `/usr/lib/x86_64-linux-gnu/polkit-mate/polkit-mate-authentication-agent-1`.

I also realised that my `mate-polkit` package comes from the upstream Ubuntu repo, so this bug is likely also affecting Ubuntu Jammy. Indeed, comparing the Jammy and Mantic packages:
https://packages.ubuntu.com/jammy/amd64/mate-polkit/filelist
https://packages.ubuntu.com/mantic/amd64/mate-polkit/filelist

Concerning setting `GDK_BACKEND=x11` in the environment, wouldn't this result in other applications also running under XWayland? I rarely have problems with other applications, and thus actually would prefer them to run under Wayland rather than XWayland.

**Comment by SoumyaRanjanPatnaik** [comment]
> . However, there's a package for it: mate-polkit-bin, which is literally just a shell script under /usr/bin calling /usr/lib/x86_64-linux-gnu/polkit-mate/polkit-mate-authentication-agent-1.

Thanks for this. This is probably the most ideal solution IMO.

**Comment by 70rc** [comment]
Ah, sorry, then I misunderstood your proposal. I thought you meant adding `GDK_BACKEND=x11` to the general environment. I think you're right, and setting it for polkit only shouldn't affect the applications connecting to polkit.

**Comment by SoumyaRanjanPatnaik** [comment]
#21 Fixes this
